version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis-demo
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build:
      context: ./RedisHashslotSharding
      dockerfile: Dockerfile
    container_name: redis-hashslot-sharding-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped
