version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AllowedRateLimitWindow=00:00:01
      - RateLimitPerBucket=10
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - ratelimiter-network
    restart: always
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 2G
    expose:
      - "80"  # This exposes the port internally to other services, not to the host
    scale: 5  # Number of replicas for scaling the service

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - ratelimiter-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 2G

  loadbalancer:
    image: nginx:latest
    ports:
      - "5000:80"  # Expose the load balancer on port 5000
    networks:
      - ratelimiter-network
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX configuration
    restart: always

networks:
  ratelimiter-network:
    driver: bridge
