version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AllowedRateLimitWindow=00:00:01
      - RateLimitPerBucket=10
    ports:
      - "5000:80"
    networks:
      - ratelimiter-network
    restart: always

networks:
  ratelimiter-network:
    driver: bridge
