version: '3.8'

services:
  urlshortener-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SnowflakeBaseUrl=http://loadbalancer
    networks:
      - system-design
    restart: always
    expose:
      - "80"  # This exposes the port internally to other services, not to the host
    scale: 1 # Number of replicas for scaling the service
    mem_limit: 2g       # ✅ Enforces 2GB RAM limit
    cpus: 1.0


  loadbalancer:
    image: nginx:latest
    ports:
      - "5000:80"  # Expose the load balancer on port 5000
    networks:
      - system-design
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX configuration
    restart: always

networks:
  system-design:
    external: true
