version: '3.8'

services:
  snowflakeapi-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MachineId=1
    networks:
      - snowflake-network
    restart: always
    expose:
      - "80"  # This exposes the port internally to other services, not to the host
    scale: 1 # Number of replicas for scaling the service
    mem_limit: 2g       # ✅ Enforces 2GB RAM limit
    cpus: 1.0

  snowflakeapi-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MachineId=2
    networks:
      - snowflake-network
    restart: always
    expose:
      - "80"
    mem_limit: 2g
    cpus: 1.0  


  loadbalancer:
    image: nginx:latest
    ports:
      - "5000:80"  # Expose the load balancer on port 5000
    networks:
      - snowflake-network
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the NGINX configuration
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - snowflake-network
    restart: always

networks:
  snowflake-network:
    driver: bridge
